package models

import (
	"regexp"
	"strings"
	"time"

	"github.com/jinzhu/gorm"

	"github.com/samueldaviddelacruz/go-job-board/hash"
	"github.com/samueldaviddelacruz/go-job-board/rand"

	"golang.org/x/crypto/bcrypt"
)

// Company represents the Company model stored in the database
type Company struct {
	gorm.Model
	Name         string `gorm:"not_null"`
	Email        string `gorm:"not null;unique_index"`
	Password     string `gorm:"-"`
	PasswordHash string `gorm:"not null"`
	Remember     string `gorm:"-"`
	RememberHash string `gorm:"not null;unique_index"`
}

// CompanyDB is used to interact with the users database.
//
// For pretty much all single user queries:
// If the user is found, we will return a nil error
// If the user is not found, we will return ErrNotFound
// If there is another error, we will return an error with
// more information about what went wrong. This may not be
// an error generated by the models package.
//
// For single user queries, any error but ErrNotFound should
// probably result in a 500 error.
type CompanyDB interface {
	// Methods for querying single users
	ByID(id uint) (*Company, error)
	ByEmail(email string) (*Company, error)
	ByRemember(token string) (*Company, error)

	// Methods for altering users
	Create(user *Company) error
	Update(user *Company) error
	Delete(id uint) error
}

// CompanyService is a set of methods used to manipulate and work
// with the user model
type CompanyService interface {
	// Authenticate will verify if the provided email address and
	// password are correct. if they are correct, the user
	// corresponding to that e  mail will be returned. Otherwise
	// you will receive either:
	// ErrNotFound, ErrPasswordIncorrect, or another error if
	// something goes wrong.
	Authenticate(email, password string) (*Company, error)

	// InitiateReset will start the reset password process
	// by creating a reset token for the user found with the
	// provided email address.
	InitiateReset(email string) (string, error)
	CompleteReset(token, newPw string) (*Company, error)
	CompanyDB
}

func NewCompanyService(db *gorm.DB, pepper, hmacKey string) CompanyService {
	ug := &userGorm{db}

	hmac := hash.NewHMAC(hmacKey)
	uv := newCompanyValidator(ug, hmac, pepper)
	return &companyService{
		CompanyDB: uv,
		pepper:    pepper,
		pwResetDB: newPwResetValidator(&pwResetGorm{db}, hmac),
	}
}

var _ CompanyService = &companyService{}

type companyService struct {
	CompanyDB
	pepper    string
	pwResetDB pwResetDB
}

// Authenticate can be used to authenticate a user with the
// provided email address and password.
// If the email provided is invalid, this will return
// nil, ErrNotFound
// if the password provided is invalid, this will return
// nil, ErrPasswordIncorrect
// If the email and password are both valid, this will return
// user,nil
// Otherwise if another error is encountered this will return
// nil,error
func (cs *companyService) Authenticate(email, password string) (*Company, error) {
	foundCompany, err := cs.ByEmail(email)
	if err != nil {
		return nil, err
	}
	err = bcrypt.CompareHashAndPassword([]byte(foundCompany.PasswordHash), []byte(password+cs.pepper))
	if err != nil {
		switch err {
		case bcrypt.ErrMismatchedHashAndPassword:
			return nil, ErrPasswordIncorrect
		default:
			return nil, err
		}
	}

	return foundCompany, nil
}

func (cs *companyService) InitiateReset(email string) (string, error) {
	user, err := cs.ByEmail(email)
	if err != nil {
		return "", err
	}

	pwr := pwReset{
		UserID: user.ID,
	}
	if err := cs.pwResetDB.Create(&pwr); err != nil {
		return "", err
	}
	return pwr.Token, nil
}
func (cs *companyService) CompleteReset(token, newPw string) (*Company, error) {
	pwr, err := cs.pwResetDB.ByToken(token)
	if err != nil {
		if err == ErrNotFound {
			return nil, ErrPwResetInvalid
		}

		return nil, err
	}

	if time.Now().Sub(pwr.CreatedAt) > (12 * time.Hour) {
		return nil, ErrPwResetInvalid
	}

	user, err := cs.ByID(pwr.UserID)

	if err != nil {
		return nil, err
	}
	user.Password = newPw
	err = cs.Update(user)
	if err != nil {
		return nil, err
	}

	cs.pwResetDB.Delete(pwr.ID)

	return user, nil
}

type userValFunc func(*Company) error

func runCompanyValFuncs(user *Company, fns ...userValFunc) error {
	for _, fn := range fns {
		if err := fn(user); err != nil {
			return err
		}
	}

	return nil
}

var _ CompanyDB = &userValidator{}

func newCompanyValidator(udb CompanyDB, hmac hash.HMAC, pepper string) *userValidator {
	return &userValidator{
		CompanyDB:  udb,
		hmac:       hmac,
		emailRegex: regexp.MustCompile(`^[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,16}$`),
		pepper:     pepper,
	}
}

type userValidator struct {
	CompanyDB
	hmac hash.HMAC
	// emailRegex is used to match email addresses. Its not
	// perfect but works well enough for now :).
	emailRegex *regexp.Regexp
	pepper     string
}

// ByEmail will normalize the email address before calling
// ByEmail on the CompanyDB field.
func (uv *userValidator) ByEmail(email string) (*Company, error) {
	user := Company{
		Email: email,
	}
	if err := runCompanyValFuncs(&user, uv.normalizeEmail); err != nil {
		return nil, err
	}

	return uv.CompanyDB.ByEmail(user.Email)
}

// ByRemember will hash the remember token and then call
// ByRemember on the subsequent CompanyDB Layer.
func (uv *userValidator) ByRemember(token string) (*Company, error) {
	user := Company{
		Remember: token,
	}
	if err := runCompanyValFuncs(&user, uv.hmacRemember); err != nil {
		return nil, err
	}
	return uv.CompanyDB.ByRemember(user.RememberHash)
}

// Create will create the provided user and backfill data
// like the ID, CreatedAt, and UpdatedAt fields.
func (uv *userValidator) Create(user *Company) error {
	err := runCompanyValFuncs(
		user,
		uv.passwordRequired,
		uv.passwordMinLength,
		uv.bcryptPassword,
		uv.passwordHashRequired,
		uv.setRememberIfUnset,
		uv.rememberMinBytes,
		uv.hmacRemember,
		uv.rememberHashRequired,
		uv.normalizeEmail,
		uv.requireEmail,
		uv.emailFormat,
		uv.emailIsAvail)
	if err != nil {
		return err
	}

	return uv.CompanyDB.Create(user)
}

// Update will hash a remember token if it is provided.
func (uv *userValidator) Update(user *Company) error {
	err := runCompanyValFuncs(user,
		uv.passwordMinLength,
		uv.bcryptPassword,
		uv.passwordHashRequired,
		uv.rememberMinBytes,
		uv.hmacRemember,
		uv.rememberHashRequired,
		uv.normalizeEmail,
		uv.requireEmail,
		uv.emailFormat,
		uv.emailIsAvail)
	if err != nil {
		return err
	}
	return uv.CompanyDB.Update(user)
}

// Delete will delete the user with the provided ID
func (uv *userValidator) Delete(id uint) error {
	var user Company
	user.ID = id
	if err := runCompanyValFuncs(&user, uv.idGreaterThan(0)); err != nil {
		return err
	}
	return uv.CompanyDB.Delete(id)
}

// bcryptPassword will hash a user's password with a
// predefined pepper (userPwPepper) and bcrypt if the
// Password field is not an empty string
func (uv *userValidator) bcryptPassword(user *Company) error {
	if user.Password == "" {
		return nil
	}
	pwBytes := []byte(user.Password + uv.pepper)
	hashedBytes, err := bcrypt.GenerateFromPassword(pwBytes, bcrypt.DefaultCost)
	if err != nil {
		return err
	}
	user.PasswordHash = string(hashedBytes)
	user.Password = ""

	return nil
}

func (uv *userValidator) hmacRemember(user *Company) error {
	if user.Remember == "" {
		return nil
	}

	user.RememberHash = uv.hmac.Hash(user.Remember)

	return nil
}

func (uv *userValidator) setRememberIfUnset(user *Company) error {
	if user.Remember != "" {
		return nil
	}
	token, err := rand.RememberToken()
	if err != nil {
		return err
	}
	user.Remember = token
	return nil
}

func (uv *userValidator) rememberMinBytes(user *Company) error {
	if user.Remember == "" {
		return nil
	}

	n, err := rand.NBytes(user.Remember)
	if err != nil {
		return err
	}

	if n < 32 {
		return ErrRememberTooShort
	}
	return nil
}

func (uv *userValidator) rememberHashRequired(user *Company) error {
	if user.RememberHash == "" {
		return ErrRememberRequired
	}

	return nil
}

func (uv *userValidator) idGreaterThan(value uint) userValFunc {
	return func(user *Company) error {
		if user.ID <= value {
			return ErrIDInvalid
		}
		return nil
	}
}

func (uv *userValidator) normalizeEmail(user *Company) error {
	user.Email = strings.ToLower(user.Email)
	user.Email = strings.TrimSpace(user.Email)
	return nil
}

func (uv *userValidator) requireEmail(user *Company) error {
	if user.Email == "" {
		return ErrEmailRequired
	}
	return nil
}

func (uv *userValidator) emailFormat(user *Company) error {
	if !uv.emailRegex.MatchString(user.Email) {
		return ErrEmailInvalid
	}
	return nil
}

func (uv *userValidator) emailIsAvail(user *Company) error {
	existing, err := uv.ByEmail(user.Email)
	if err == ErrNotFound {
		// Email address is not taken
		return nil
	}

	if err != nil {
		return err
	}
	// We found a user w/ this email address...
	// If the found user has the same ID as this user, it is
	// an update and this is the same user.
	if user.ID != existing.ID {
		return ErrEmailTaken
	}
	return nil
}

func (uv *userValidator) passwordMinLength(user *Company) error {
	if user.Password == "" {
		return nil
	}
	if len(user.Password) < 8 {
		return ErrPasswordTooShort
	}

	return nil
}

func (uv *userValidator) passwordRequired(user *Company) error {
	if user.Password == "" {
		return ErrPasswordRequired
	}

	return nil
}

func (uv *userValidator) passwordHashRequired(user *Company) error {
	if user.PasswordHash == "" {
		return ErrPasswordRequired
	}

	return nil
}

var _ CompanyDB = &userGorm{}

type userGorm struct {
	db *gorm.DB
}

// ByID will look up a user with the provided ID.
// If the user is found, we will return a nil error
// If the user is not found, we will return ErrNotFound
// If there is another error, we will return an error with
// more information about what went wrong. This may not be
// an error generated by the models package.
//
// As a general rule, any error but ErrNotFound should
// probably result in a 500 error.
func (ug *userGorm) ByID(id uint) (*Company, error) {
	var user Company
	db := ug.db.Where("id = ?", id)
	err := first(db, &user)

	return &user, err

}

// ByEmail looks up a user with a given email address and
// returns that user.
// If the user is found, we will return a nil error
// If the user is not found, we will return ErrNotFound
// If there is another error, we will return an error with
// more information about what went wrong. This may not be
// an error generated by the models package.
//
// As a general rule, any error but ErrNotFound should
// probably result in a 500 error.
func (ug *userGorm) ByEmail(email string) (*Company, error) {
	var user Company
	db := ug.db.Where("email = ?", email)
	err := first(db, &user)

	return &user, err
}

// ByRemember looks up a user with the given remember token
// and returns that user, This method expects the remember
// token to already be hashed.
// Errors are the same as ByEmail
func (ug *userGorm) ByRemember(rememberHash string) (*Company, error) {
	var user Company

	db := ug.db.Where("remember_hash = ?", rememberHash)
	err := first(db, &user)

	return &user, err
}

// Create will create the provided user and backfill data
// like the ID, CreatedAt, and UpdatedAt fields.
func (ug *userGorm) Create(user *Company) error {
	return ug.db.Create(user).Error
}

// Update will update the provided user with all of the data
// in the provided the user object.
func (ug *userGorm) Update(user *Company) error {
	return ug.db.Save(user).Error
}

// Delete will delete the user with the provided ID
func (ug *userGorm) Delete(id uint) error {
	user := Company{Model: gorm.Model{ID: id}}
	return ug.db.Delete(&user).Error
}

// first will query using the provided gorm.DB and it will
// get the first item returned and place it into dst(if dst is a pointer). If
// nothing is found in the query, it will return ErrNotFound
func first(db *gorm.DB, dst interface{}) error {
	err := db.First(dst).Error
	if err == gorm.ErrRecordNotFound {
		return ErrNotFound
	}
	return err
}
